### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `TestUI`.

### ISSUE THREAD

**Issue by niranjanbprajapati** [react-component/m-date-picker#10]
Hi @yiminghe,

I am trying to integrate your code in my react native project, which is cross platform application for android and ios. 

Also in my project all the files are .js files, and your example was in .tsx files, if there are any changes meant to be done for .js files please do let me know.

I am getting the following error: 

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `TestUI`.

Following is my code, please let me know if i am making any mistake in integrating the code:

`'use strict';
import React, {
    View,
    Component,
    StyleSheet,
    TouchableHighlight,
    ScrollView,
    Text,
    Platform,
    DatePickerAndroid,
    TouchableWithoutFeedback,
    DatePickerIOS,
    TimePickerAndroid,
    TextInput,
    TouchableOpacity,
    PropTypes,
    Image
} from 'react-native';

import {
    Card,
    Button
} from 'react-native-material-design';

import {
    PopPicker,
    PopupStyles
} from 'rmc-date-picker';
import moment from 'moment';

import enUs from 'rmc-date-picker/lib/locale/en_US';
import 'moment/locale/zh-cn';
import 'moment/locale/en-gb';

const minDate = moment([2015, 8, 1, 0, 0, 0]);
const maxDate = moment([2018, 1, 1, 22, 0, 0]);
const now = moment();

minDate.locale('en-gb').utcOffset(0);
maxDate.locale('en-gb').utcOffset(0);
now.locale('en-gb').utcOffset(0);

var styles = StyleSheet.create({
    mainContainer: {
        marginTop: (Platform.OS === 'ios') ? 64 : 56,
        flex: 1,
        padding: 20,
        backgroundColor: '#E2E2E2'
    },
    dateButton: {
        backgroundColor: '#FFFFFF',
        height: 35,
        width: 90,
        borderRadius: 3,
        margin: 5,
        alignItems: 'center',
        justifyContent: 'center',
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: .7,
        shadowColor: "black",
    },
    buttonContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
});
function format(date) {
  return date.format('YYYY-MM-DD HH:mm');
}
class TestUI extends React.Component { 	
    constructor() {
        super();
        this.state = {           
            date: null, //rcm date picker
        }
    }   
    onChange(date) {
        console.log('onChange', format(date));
        this.setState({
            date,
        });
    };
    onDismiss() {
        console.log('onDismiss');
    };
    onPickerChange(date) {
        console.log('onPickerChange', format(date));
    };
    show() {
        console.log('my click');
    };    
    render() {       
        const {date} = this.state;
        var dateButtonIOS = (<View style={styles.dateButton}><TouchableOpacity
            onPress={this.show} activeOpacity={0.5}>
            <View >
                <Text pointerEvents="none"
                    style={{ textAlign: 'center', color: '#000000', backgroundColor: '#FFFFFF', fontWeight: '600', fontSize: 14 }}>
                    {date && format(date) || 'Date of Birth'}
                </Text>
            </View>
        </TouchableOpacity></View>);
        var dateButtonAndroid = (<View style={styles.buttonContainer} activeOpacity={0.5}><Button
            text={date && format(date) || 'Date of Birth'}
            raised={true}
            overrides={{ textColor: '#000000', backgroundColor: '#FFFFFF', rippleColor: '#585858' }}
            onPress={this.show} /></View>
        );
        var dateButton = Platform.OS === 'ios' ? dateButtonIOS : dateButtonAndroid;       
        return (
            <View style = {styles.mainContainer}>
                <View>
                    <PopPicker
                        styles={PopupStyles}
                        title="Date of Birth"
                        date= {date || now}
                        minDate={minDate}
                        maxDate={maxDate}
                        mode='date'
                        locale={enUs}
                        onPickerChange={this.onPickerChange}
                        onDismiss={this.onDismiss}
                        onChange={this.onChange}
                        >
                        {dateButton}
                    </PopPicker>
                </View>
            </View>
        );
    }
}

export default TestUI;`

Please help me out.

**Comment by yiminghe** [comment]
import specified module

```js
import PopPicker from 'rmc-date-picker/lib/Popup'
```

**Comment by niranjanbprajapati** [comment]
Thanks @yiminghe  that solution worked but the date picker is not opening. Do I have to write some code in show() method. Sorry for asking silly question i am new to react-native.

**Comment by yiminghe** [comment]
checkout https://github.com/react-component/m-date-picker/tree/master/examples/react-native
