### ISSUE TITLE
期望mode属性增加month

### ISSUE THREAD

**Issue by imetric** [react-component/m-date-picker#13]
这个就选择时期时，就只选择年和月。

**Comment by yiminghe** [comment]
welcome pr

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/358#issuecomment-269444656

建议像 https://mobile.ant.design/components/picker/ Picker 组件一样增加`cols` 属性，展现上强制截断相应设置的列数。在`cols={2} mode={'date'}`情况只展示 “年/月”；在`cols={4} mode={'datetime'}`情况只展示 “年/月/日/时” 不展示最后一列“分钟”。这样几乎能灵活覆盖所有个性化展示需求，改动成本也小。

**Comment by CoderPXin** [comment]
目前选择月份的需求很普遍建议支持选择月份

**Comment by paranoidjk** [comment]
最新版已经支持
https://github.com/react-component/m-date-picker/commit/910676ce8c71fc17f2c05a432afe7346efcc2c38

**Comment by yozman** [comment]
@paranoidjk @yiminghe 
year, month 模式统统不好使啊。。。
测试过没有。。。

**Comment by warmhug** [comment]
@yozman 
![image](https://user-images.githubusercontent.com/2011119/30530969-aed09a4c-9c7d-11e7-94d6-fe8e7a7ddb08.png)

**Comment by yozman** [comment]
这是 web，
rn 瞅瞅。。

**Comment by yozman** [comment]
我這邊真的是一片空白。。date 和 datetime 是好使的
