### ISSUE TITLE
时间切换 bug 

### ISSUE THREAD

**Issue by warmhug** [react-component/m-date-picker#14]
在 mode="date" 状态下：月份、日期 都 切到小于 minDate 设置的 月份、日期，年份从 大于 minDate 设置的年份、切到 minDate 的年份，月份会变为 minDate 设置的月份、但日期不会变。

相应最大状态也可能有问题。。

**Comment by yiminghe** [comment]
不懂什么意思，请提供录像或 pr

**Comment by warmhug** [comment]
示例 https://mobile.ant.design/components/date-picker/  demo 里的第一个，最大最小日期如下
```js
const maxDate = moment('2018-12-03 +0800', 'YYYY-MM-DD Z').utcOffset(8);
const minDate = moment('2015-08-06 +0800', 'YYYY-MM-DD Z').utcOffset(8);
```
先切换到 2016 - 2 - 2 ，再只把 年份切换到 2015 年，月份变为变为 8 是对的，天仍是 2 ，应该变为 minDate 设置的 6 

![gg](https://cloud.githubusercontent.com/assets/2011119/20425839/606a23c4-adb7-11e6-9a34-ed23dad3fcb1.gif)
