### ISSUE TITLE
How can i customize the length of "rmc-picker-item" items?

### ISSUE THREAD

**Issue by SF-Terry** [react-component/m-date-picker#18]
# How can i customize the length of "rmc-picker-item" items?
 Default length is 7,what i prefer is 3 or 5 for that i'd like to use two Datepickers in one page. how can i customize the length of "rmc-picker-item" items to 3 or 5?
Screeshot here:
![image](https://cloud.githubusercontent.com/assets/19622736/20827718/c1a26b7c-b8ae-11e6-96c2-2cdfdc3d79cd.png)
Thanks.

**Comment by jonespen** [comment]
I think this is pretty much hard coded into the m-picker library, ref
* https://github.com/react-component/m-picker/blob/master/src/NativePicker.android.tsx#L68
* https://github.com/react-component/m-picker/blob/master/assets/index.less#L8

**Comment by SF-Terry** [comment]
@jonespen At last,i used a toggle button to fit my requirement. Anyway, thank u
