### ISSUE TITLE
版本5.3.3 去掉了web的支持？

### ISSUE THREAD

**Issue by allroad88888888** [react-component/m-date-picker#23]
5.1版本使用
import DatePicker from 'rmc-date-picker/lib/index.web';
5.3版本使用
//import a from "rmc-date-picker";  
这个报react-native没有

**Comment by warmhug** [comment]
没有，只是去掉了 web 后缀

**Comment by allroad88888888** [comment]
5.3版本用 
import DatePicker from 'rmc-date-picker/lib/index';
编译报错
ERROR in ./~/rmc-picker/lib/MultiPicker.js
Module not found: Error: Can't resolve 'react-native'

ERROR in ./~/rmc-picker/lib/NativePicker.ios.js
Module not found: Error: Can't resolve 'react-native'


5.1版本使用
import DatePicker from 'rmc-date-picker/lib/index.web';
这个能正常编译通过的

**Comment by yiminghe** [comment]
https://github.com/react-component/m-date-picker#usage
