### ISSUE TITLE
请问是否支持 选个可选时间段？

### ISSUE THREAD

**Issue by xjdata** [react-component/m-date-picker#26]
请问是否支持 选个可选时间段？

比如 控件只显示 09:00 -> 11:30 或者 14:00 -> 17:00 这2个范围内容的时间呢？

谢谢。

**Comment by warmhug** [comment]
minDate  maxDate 设置

**Comment by xjdata** [comment]
@warmhug  这个我知道....  我的意思是  同一个控件下  [ 09:00 -> 11:30 , 14:00 -> 17:00 ]  `2个范围`

**Comment by warmhug** [comment]
参考 demo ，自己做上层封装实现吧
