### ISSUE TITLE
设置minuteStep = 5后时间显示不对

### ISSUE THREAD

**Issue by NTmemoir** [react-component/m-date-picker#27]
DatePicker 设置minuteStep 为5后，选择时间时（譬如当前时间为14:46）,控件弹出后默认选中的为14:00,

**Comment by warmhug** [comment]
你这个情况、不需要设置 minuteStep ，它只是展示上的步长、可以用来限制只能选择它设置的分钟点，
而跟当前或你传入的时间里的分钟数没有关系。

**Comment by GuiYangGan** [comment]
既然我设置了minuteStep为5，（当前时间为14:46）而控件弹出后默认选中的为14:00，那我直接点确定时，应该是返回控件默认选中的时间14:00，而不应该再返回当前时间了

**Comment by GuiYangGan** [comment]
否则用户会很困惑，为什么这里明明选中的是14:00，我确定后反而变成了14:46？
