### ISSUE TITLE
日期计算错误

### ISSUE THREAD

**Issue by warmhug** [react-component/m-date-picker#3]
http://react-component.github.io/m-date-picker/examples/simple.html
![image](https://cloud.githubusercontent.com/assets/2011119/16147850/5b3d1122-34b8-11e6-8d3e-d65bf7989653.png)

**Comment by yiminghe** [comment]
以后要直接提 pr https://github.com/react-component/m-date-picker/commit/a3e5e5de83c2c634b4fa690e51fe3787dfa1338e
