### ISSUE TITLE
在手机浏览器上无法弹出选择框

### ISSUE THREAD

**Issue by fengshanjian** [react-component/m-date-picker#32]
在手机浏览器上无法弹出选择框，测试手机iphone6  ios 10.3
android 三星 7.0

在mac的chrome以及safari显示正常

**Comment by fengshanjian** [comment]
原因找到了，放置到iScroll中会出现这种情况

**Comment by warmhug** [comment]
date-picker 本身依赖了个类似于 iscroll 的 zscroll 。麻烦自己排查下原因吧。
