### ISSUE TITLE
寻找不到方法year

### ISSUE THREAD

**Issue by KaKmi** [react-component/m-date-picker#33]
从npm 下载下来使用，运行的时候报错
![image](https://user-images.githubusercontent.com/12822810/28915759-c65a2676-7872-11e7-9ea6-fe30261ee80c.png)
![image](https://user-images.githubusercontent.com/12822810/28915850-fd2eadca-7872-11e7-84f3-896a3a8aa4ec.png)

我看github中的代码 是
![image](https://user-images.githubusercontent.com/12822810/28915971-511e0228-7873-11e7-9885-3e06ebdf6bf4.png)

**Comment by KaKmi** [comment]
看了demo用的6.0版本，重新安装后可以跑起来

**Comment by hhking** [comment]
6.0 版本没有发布到npm吧

**Comment by warmhug** [comment]
ref #47
