### ISSUE TITLE
PopPicker minDate 设置为1990-1-1时，在手机上面，选择年的地方出现了问题。

### ISSUE THREAD

**Issue by zhea55** [react-component/m-date-picker#4]
如题

**Comment by yiminghe** [comment]
具体点，能否给个线上 demo

**Comment by zhea55** [comment]
http://react-component.github.io/m-date-picker/examples/popup.html

就这个例子里面，将minDate时间设小，因为我们的业务是设置用户的生日。

然后选取199几年的时候，界面显示的和实际选择的数据不相符。

**Comment by yiminghe** [comment]
升级到最新试下，master 不能重现
