### ISSUE TITLE
use12Hours移动端问题

### ISSUE THREAD

**Issue by srygg** [react-component/m-date-picker#40]
use12Hours在安卓和ios好像不起作用

**Comment by warmhug** [comment]
use 6.0.0-alpha.5

**Comment by srygg** [comment]
![simulator screen shot sep 1 2017 8 32 07 am](https://user-images.githubusercontent.com/8388269/29970057-1566b81c-8ef1-11e7-9eda-1627908b428f.png)

I got this issue after installing the alpha version, can you look at that? Thank you.

**Comment by silentcloud** [comment]
use 6.0.0-alpha.5 测试了没问题

**Comment by srygg** [comment]
@silentcloud  就是alpha.5， 我试了所有alpha版本都是这个错误。其他正式版本没有问题。不过我用m-picker自己自定义了一个，没啥问题

**Comment by paranoidjk** [comment]
@srygg 检查下你是否自己设置了 `props. minDate`

给出可复现代码或 demo。不然无法排查问题

**Comment by srygg** [comment]
@paranoidjk  还是你会玩， 时间格式有点问题

**Comment by paranoidjk** [comment]
@warmhug 可以考虑 dev 环境下对 props 代码校验 https://github.com/react-component/tabs/blob/7f78a1668fb034e9cc85b62d19df4e9ce1c516ee/src/TabBarMixin.js#L38  最少 proptype 或 ts  interface 校验要有
