### ISSUE TITLE
date.year is not a function 

### ISSUE THREAD

**Issue by XiaYongjie** [react-component/m-date-picker#47]
"react": "16.0.0-alpha.12",
  "react-native": "0.47.0",
date.year is not a function  
DatePicker.js:231：31

**Comment by warmhug** [comment]
https://github.com/react-component/m-date-picker/blob/master/HISTORY.md#6x
![image](https://user-images.githubusercontent.com/2011119/30838662-89c09b5c-a232-11e7-9648-88ae219af1d5.png)
No moment.js, No `.year()` method.

**Comment by XiaYongjie** [comment]
@warmhug  谢谢

**Comment by Muriel-Gasparini** [comment]
> No moment.js, No `.year()` method.

Date also has no year method
