### ISSUE TITLE
模块必须依赖 react-native 才能运行么？

### ISSUE THREAD

**Issue by maskzh** [react-component/m-date-picker#6]
![](http://elliott.b0.upaiyun.com/2016-07-05_12:17:31.jpg)

**Comment by yiminghe** [comment]
https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L76

.web.js 优先

**Comment by warmhug** [comment]
为什么不明确默认指向web.js ？#7
