### ISSUE TITLE
必须要install react-native?而我只是要用于web项目中。

### ISSUE THREAD

**Issue by shenzhigang** [react-component/m-date-picker#8]
Module not found: Error: Cannot resolve module 'react-native' in /home/shenzhigang/svn/App/trunk/node_modules/rmc-date-picker/lib
 @ ./~/rmc-date-picker/lib/DatePicker.js 7:19-42

必须要install react-native?而我只是要用于web项目中。

**Comment by yiminghe** [comment]
https://github.com/react-component/m-date-picker/issues/6
